version: "3.8"

services:
  backend:
    container_name: namles-backend
    build:
      context: ./server
      dockerfile: Dockerfile
      # prevents cache from creating dangling images
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "8082:8080"
    restart: unless-stopped
    volumes:
      - upload:/upload
    environment:
      DATABASE_CONNECTION: mongodb://db/olivia
    depends_on:
      - db

  db:
    container_name: namles-db
    image: mongo:4.0-xenial
    ports:
      - "2777:27017"
    restart: unless-stopped
    volumes:
      - phone:/data/db

  web:
    container_name: namles-web
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "3055:80"
    restart: unless-stopped
    volumes:
      - ./admin:/app
      - /app/node_modules
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend



volumes:
  phone:
  upload:
